sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cxm5cVBErvhFumKndOpi1FAz/90noPqSx8M2gJoCgvZklB/Y3IEDYjLzFoFchQqaUubT/6XZgpr16OyQF5QKp5dmrLVl5cuj+bHF9w5tGfbT49XuLPJcxQAFKqM8JmFxvHckH2T3GNdtnp6NPQdf2q+xUryLfRDOVcEUntB1NWGMeAheYdr0nSxGognhcqfeQb6VZvLI3jROEEcKduC2Sh7gq4nv3ACoNdL4GsQ/vRJbyfPQZwZnYRyuIhOozlENGTbKFqnkgHx6gZqzrhOBD8wj5Ci2jr/+uSBgSEr8QNIW5ZS3lJ6oT/rLoyKE6G5vbadfYfadiUZt5L41a5lOAlx1skwcP2Z+l3sSstWqMxO9AIbhtH1dXV+w724TxvnR8OOajAa4IsvH2VTvJZ+VTrk5Zklt3FJGejMwv0FWhk33qt8UWVrDJCALdW/g1oRDckeMr4rIP4+itu7xRiAJwq8AhPsHfP7yZzZ2Q5By9N/+qRbr6RJmb2ebwwG7uhdzgtOh8fwESaSFMxat3B2GamZ/7woBZRxrWcnkawOBnJ+S5piHYOaaoqhSpuqU2rMBGNmiHrL9Toz8PWKvK+9J/KpdyrTNuNIYO/O1B9SZnHp1p1ehukDQ3xpKktR2RqGZo7zBKBSuHOzIig1Ia06m1mRC8kbAK4DANUhb56OC/bA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Boy-Scouts-Patrol_5602
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy